version: "3.7"

services:
  application:
    build:
      context: ./
      dockerfile: src/main/docker/Dockerfile
    container_name: sandbox
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - SPRING_DATASOURCE_URL=jdbc:postgresql://employeedb:5432/employees
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - employeedb

  employeedb:
    image: postgres
    container_name: employeedb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=employees
    ports:
      - 5432:5432
    restart: always
